Certbot ipv64 dnschallenge
sunweaver/nextcloud-high-performance-backend-setup pull request #159
Opened 2024-10-24 09:39 UTC by lodzen

2025-02-11 10:19 UTC, sunweaver requested changes
Thanks @lodzen for your pull request. I have some change requests.

Can you also stash your commit history and make one commit out of it? Thanks.

If all adjustments have been made, the remaining question will be where to obtain a better maintained version of certbot-dns-ipv64 from?

2025-02-11 10:19 UTC, sunweaver commented on src/setup-certbot.sh
> +			git clone https://github.com/XonaTheProtogen/certbot-dns-ipv64.git 2>&1 | tee -a $LOGFILE_PATH
@lodzen The certbot-dns-ipv64 plugin for certbot seems unmaintained (two years no commits). Is there a newer source available maybe?

2025-02-11 10:19 UTC, sunweaver commented on setup-nextcloud-hpb.sh
> +CERTBOT_AUTH_METHOD="" # Ask user
Please amend white-spaces here, all comment hashes should be in one column.

2025-02-11 10:19 UTC, sunweaver commented on setup-nextcloud-hpb.sh
> +				CERTBOT_AUTH_METHOD="http"
The log messages don't match what is happening in the code. Change to "Cerbot AUTH method selected is: 'http'" (or similar)

2025-02-11 10:19 UTC, sunweaver commented on setup-nextcloud-hpb.sh
> +				CERTBOT_AUTH_METHOD="ipv64"
dito

2025-02-11 10:19 UTC, sunweaver commented on setup-nextcloud-hpb.sh
> +	log "Using '$CERTBOT_AUTH_METHOD' for DRY_RUN".
should be: log "Using '$CERTBOT_AUTH_METHOD' for CERTBOT_AUTH_METHOD".

2025-02-11 10:19 UTC, sunweaver commented on src/setup-certbot.sh
> +			--chain-path "$SSL_CHAIN_PATH_RSA" -authenticator dns-ipv64 --dns-ipv64-credentials "/home/daniel/certbot-dns-ipv64/credentials.ini")
Don't put your full local home path here. This needs to work on anyone's machine! I.e. you have to put some relative path name here.

2025-02-11 10:19 UTC, sunweaver commented on src/setup-certbot.sh
> +			log "Unsupported AUTH Method $CERTBOT_AUTH_METHOD!" >&2
maybe better "Unsupported Certbot AUTH method: $CERTBOT_AUTH_METHOD!"

2025-02-11 10:20 UTC, sunweaver commented
@lodzen Also: sorry for the looooong delay until I reviewed this.

2025-02-11 14:05 UTC, dzatoah commented on settings.sh
> +
I'm unsure if this works overall, since coturn requires public internet access, I think.
The documentation clearly states, that we won't support servers using NAT.

2025-02-11 14:12 UTC, lodzen commented on settings.sh
> +
I can only say that i run this setup in my homelab and it works good.

2025-02-11 14:20 UTC, dzatoah commented on settings.sh
> +
Very interesting. I've never looked into that. Maybe this is a feature we can build into this script, instead of just closing tickets for people with a NAT-setup.. ;)

2025-03-12 11:34 UTC, lodzen commented on src/setup-certbot.sh
> +			git clone https://github.com/XonaTheProtogen/certbot-dns-ipv64.git 2>&1 | tee -a $LOGFILE_PATH
I created an own fork for the repo and worked on a branch to push the changes

2025-03-12 11:34 UTC, lodzen commented on setup-nextcloud-hpb.sh
> +CERTBOT_AUTH_METHOD="" # Ask user
Updated

2025-03-12 11:34 UTC, lodzen commented on setup-nextcloud-hpb.sh
> +				CERTBOT_AUTH_METHOD="http"
Updated

2025-03-12 11:34 UTC, lodzen commented on setup-nextcloud-hpb.sh
> +				CERTBOT_AUTH_METHOD="ipv64"
Updated

2025-03-12 11:34 UTC, lodzen commented on setup-nextcloud-hpb.sh
> +	log "Using '$CERTBOT_AUTH_METHOD' for DRY_RUN".
Updated

2025-03-12 11:34 UTC, lodzen commented on src/setup-certbot.sh
> +			--chain-path "$SSL_CHAIN_PATH_RSA" -authenticator dns-ipv64 --dns-ipv64-credentials "/home/daniel/certbot-dns-ipv64/credentials.ini")
Fixed

2025-03-12 11:34 UTC, lodzen commented on src/setup-certbot.sh
> +			log "Unsupported AUTH Method $CERTBOT_AUTH_METHOD!" >&2
Updated

2025-10-08 16:00 UTC, merged